[custom]
; custom ban list
ruleset=🛑 隐私广告,https://gh.monlor.com/https://raw.githubusercontent.com/monlor/subconverter-rules/main/rules/ban.ini

; Direct
ruleset=🇨🇳 中国直连,https://gh.monlor.com/https://raw.githubusercontent.com/monlor/subconverter-rules/main/rules/whitelist.ini,no-resolve
ruleset=🧱 GFW列表,https://gh.monlor.com/https://raw.githubusercontent.com/monlor/subconverter-rules/main/rules/blacklist.ini

ruleset=DIRECT,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🇨🇳 中国直连,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🇨🇳 中国直连,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list

; Advertisement
ruleset=🛑 隐私广告,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🛑 隐私广告,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
; ruleset=🛑 隐私广告,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
ruleset=🛑 隐私广告,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
ruleset=🛑 隐私广告,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list

; region: https://gspe1-ssl.ls.apple.com/pep/gcc
ruleset=🗺️ 苹果区域,https://gh.monlor.com/https://raw.githubusercontent.com/monlor/subconverter-rules/main/rules/AppleRegion.ini
ruleset=🔌 常见端口,https://gh.monlor.com/https://raw.githubusercontent.com/monlor/subconverter-rules/main/rules/tcpports.ini
ruleset=📶 VoWiFi,https://gh.monlor.com/https://raw.githubusercontent.com/monlor/subconverter-rules/main/rules/vowifi.ini

ruleset=💳 银行钱包,https://gh.monlor.com/https://raw.githubusercontent.com/monlor/subconverter-rules/main/rules/paypal.ini
ruleset=💳 银行钱包,https://gh.monlor.com/https://raw.githubusercontent.com/monlor/subconverter-rules/main/rules/wallet.ini
ruleset=🤖 AI服务,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=🤖 AI服务,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
; ruleset=🏃‍♂️ SpeedTest,https://gh.monlor.com/https://raw.githubusercontent.com/LM-Firefly/Rules/master/SpeedTest.list
; ruleset=📲 无忧行,https://gh.monlor.com/https://raw.githubusercontent.com/monlor/subconverter-rules/main/rules/jegotrip.ini

; 中国直连
ruleset=📢 谷歌服务,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🇨🇳 中国直连,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list

;流媒体
ruleset=📺 巴哈姆特,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=🌍 流媒体服务,https://gh.monlor.com/https://raw.githubusercontent.com/monlor/subconverter-rules/main/rules/globalmedia.ini
; ruleset=🎥 Netflix,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
; ruleset=📀 HboMax,https://gh.monlor.com/https://raw.githubusercontent.com/monlor/subconverter-rules/main/rules/hbomax.ini
; ruleset=🎶 TikTok,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TikTok.list
;ruleset=🌏 ChinaMedia,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list

ruleset=📢 谷歌服务,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
ruleset=📢 谷歌服务,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=Ⓜ️ 微软服务,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=Ⓜ️ 微软服务,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=🎮 游戏平台,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list

ruleset=🧱 GFW列表,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🇨🇳 中国直连,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🇨🇳 中国直连,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🇨🇳 中国直连,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🇨🇳 中国直连,[]GEOIP,CN

;final
ruleset=🐟 其他服务,[]FINAL
;设置规则标志位

# `[]🚀 默认节点`[]♻️ 自动选择`[]🚀 手动选择`[]DIRECT`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇩🇪 德国节点`[]🇬🇧 英国节点`[]🇦🇺 澳洲节点`[]🇨🇳 中国节点
# `[]DIRECT`[]🚀 默认节点`[]♻️ 自动选择`[]🚀 手动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇩🇪 德国节点`[]🇬🇧 英国节点`[]🇦🇺 澳洲节点`[]🇨🇳 中国节点

;设置分组标志位
custom_proxy_group=🚀 默认节点`select`[]♻️ 自动选择`[]🚀 手动选择`[]DIRECT`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇩🇪 德国节点`[]🇬🇧 英国节点`[]🇦🇺 澳洲节点`[]🇨🇳 中国节点`[]🕹️ 游戏节点
custom_proxy_group=🚀 手动选择`select`.*
custom_proxy_group=♻️ 自动选择`url-test`(?i)^(?!.*(家宽|5G网络|星链|住宅|游戏|抓包)).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=📢 谷歌服务`select`[]🇺🇲 美国节点`[]🚀 默认节点`[]♻️ 自动选择`[]🚀 手动选择`[]DIRECT`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇩🇪 德国节点`[]🇬🇧 英国节点`[]🇦🇺 澳洲节点
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 默认节点`[]♻️ 自动选择`[]🚀 手动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇩🇪 德国节点`[]🇬🇧 英国节点`[]🇦🇺 澳洲节点`[]🇨🇳 中国节点
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 默认节点`[]♻️ 自动选择`[]🚀 手动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇩🇪 德国节点`[]🇬🇧 英国节点`[]🇦🇺 澳洲节点`[]🇨🇳 中国节点

custom_proxy_group=💳 银行钱包`select`[]🇸🇬 新加坡节点`[]🚀 默认节点`[]♻️ 自动选择`[]🚀 手动选择`[]DIRECT`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇩🇪 德国节点`[]🇬🇧 英国节点`[]🇦🇺 澳洲节点`[]🇨🇳 中国节点`.*
custom_proxy_group=🤖 AI服务`select`[]🇺🇲 美国节点`[]🚀 默认节点`[]♻️ 自动选择`[]🚀 手动选择`[]DIRECT`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇩🇪 德国节点`[]🇬🇧 英国节点`[]🇦🇺 澳洲节点`.*

custom_proxy_group=🌍 流媒体服务`select`[]🚀 默认节点`[]♻️ 自动选择`[]🚀 手动选择`[]DIRECT`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇩🇪 德国节点`[]🇬🇧 英国节点`[]🇦🇺 澳洲节点`[]🇨🇳 中国节点
custom_proxy_group=📺 巴哈姆特`select`[]🇹🇼 台湾节点`[]🚀 默认节点`[]🚀 手动选择`[]DIRECT
custom_proxy_group=🎮 游戏平台`select`[]🚀 默认节点`[]♻️ 自动选择`[]🚀 手动选择`[]DIRECT`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇩🇪 德国节点`[]🇬🇧 英国节点`[]🇦🇺 澳洲节点`[]🇨🇳 中国节点
custom_proxy_group=🗺️ 苹果区域`select`[]🇺🇲 美国节点`[]🚀 默认节点`[]♻️ 自动选择`[]🚀 手动选择`[]DIRECT`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇩🇪 德国节点`[]🇬🇧 英国节点`[]🇦🇺 澳洲节点`[]🇨🇳 中国节点`.*
custom_proxy_group=🔌 常见端口`select`[]DIRECT`[]🚀 默认节点`[]♻️ 自动选择`[]🚀 手动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇩🇪 德国节点`[]🇬🇧 英国节点`[]🇦🇺 澳洲节点`[]🇨🇳 中国节点`.*
custom_proxy_group=📶 VoWiFi`select`.*


custom_proxy_group=🛑 隐私广告`select`[]REJECT`[]DIRECT`[]🚀 手动选择
custom_proxy_group=🇨🇳 中国直连`select`[]DIRECT`[]🇨🇳 中国节点`[]🚀 默认节点`[]♻️ 自动选择`[]🚀 手动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇩🇪 德国节点`[]🇬🇧 英国节点`[]🇦🇺 澳洲节点
custom_proxy_group=🧱 GFW列表`select`[]🚀 默认节点`[]♻️ 自动选择`[]🚀 手动选择`[]DIRECT`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇩🇪 德国节点`[]🇬🇧 英国节点`[]🇦🇺 澳洲节点`[]🇨🇳 中国节点
custom_proxy_group=🐟 其他服务`select`[]🚀 默认节点`[]♻️ 自动选择`[]🚀 手动选择`[]DIRECT`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇩🇪 德国节点`[]🇬🇧 英国节点`[]🇦🇺 澳洲节点`[]🇨🇳 中国节点

custom_proxy_group=🇨🇳 中国节点`url-test`(?i)^(?!.*(家宽|5G网络|星链|住宅|游戏|抓包|HOME|GAME|FORWARD|实验)).*(中国|CN).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇭🇰 香港节点`url-test`(?i)^(?!.*(家宽|5G网络|星链|住宅|游戏|抓包|HOME|GAME|FORWARD|实验)).*(香港|港|HK|Hong Kong).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇹🇼 台湾节点`url-test`(?i)^(?!.*(家宽|5G网络|星链|住宅|游戏|抓包|HOME|GAME|FORWARD|实验)).*(台湾|台北|TW|Taiwan).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(?i)^(?!.*(家宽|5G网络|星链|住宅|游戏|抓包|HOME|GAME|FORWARD|实验)).*(日本|东京|大阪|泉日|埼玉|JP|Japan).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`(?i)^(?!.*(家宽|5G网络|星链|住宅|游戏|抓包|HOME|GAME|FORWARD|实验)).*(美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡节点`url-test`(?i)^(?!.*(家宽|5G网络|星链|住宅|游戏|抓包|HOME|GAME|FORWARD|实验)).*(新加坡|坡|狮城|SG|Singapore).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇩🇪 德国节点`url-test`(?i)^(?!.*(家宽|5G网络|星链|住宅|游戏|抓包|HOME|GAME|FORWARD|实验)).*(德国|DE|Germany).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇬🇧 英国节点`url-test`(?i)^(?!.*(家宽|5G网络|星链|住宅|游戏|抓包|HOME|GAME|FORWARD|实验)).*(英国|UK|United Kingdom).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇦🇺 澳洲节点`url-test`(?i)^(?!.*(家宽|5G网络|星链|住宅|游戏|抓包|HOME|GAME|FORWARD|实验)).*(澳洲|澳大利亚|AU|Australia).*$`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🕹️ 游戏节点`url-test`(游戏|GAME)`http://www.gstatic.com/generate_204`300,,50
enable_rule_generator=true
overwrite_original_rules=true
