[custom]
; custom ban list
ruleset=🛑 Advert,https://gh.monlor.com/https://raw.githubusercontent.com/monlor/subconverter-rules/main/rules/ban.ini

; Direct
ruleset=🎯 Direct,https://gh.monlor.com/https://raw.githubusercontent.com/monlor/subconverter-rules/main/rules/whitelist.ini
ruleset=🚀 Default,https://gh.monlor.com/https://raw.githubusercontent.com/monlor/subconverter-rules/main/rules/blacklist.ini

ruleset=🎯 Direct,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 Direct,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list

; Advertisement
ruleset=🛑 Advert,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🛑 Advert,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🛑 Advert,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
ruleset=🛑 Advert,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
ruleset=🛑 Advert,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list

; region: https://gspe1-ssl.ls.apple.com/pep/gcc
ruleset=🗺️ AppleRegion,https://gh.monlor.com/https://raw.githubusercontent.com/monlor/subconverter-rules/main/rules/AppleRegion.ini
ruleset=🔌 TCPPorts,https://gh.monlor.com/https://raw.githubusercontent.com/monlor/subconverter-rules/main/rules/tcpports.ini

ruleset=💳 Wallet,https://gh.monlor.com/https://raw.githubusercontent.com/monlor/subconverter-rules/main/rules/paypal.ini
ruleset=💳 Wallet,https://gh.monlor.com/https://raw.githubusercontent.com/monlor/subconverter-rules/main/rules/wallet.ini
ruleset=🤖 AITools,https://gh.monlor.com/https://raw.githubusercontent.com/monlor/subconverter-rules/main/rules/ai.ini

ruleset=🇨🇳 CNService,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🇨🇳 CNService,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🇨🇳 CNService,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🇨🇳 CNService,[]GEOIP,CN

;流媒体
ruleset=📺 Bahamut,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=🌍 Streaming,https://gh.monlor.com/https://raw.githubusercontent.com/monlor/subconverter-rules/main/rules/globalmedia.ini
; ruleset=🎥 Netflix,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
; ruleset=📀 HboMax,https://gh.monlor.com/https://raw.githubusercontent.com/monlor/subconverter-rules/main/rules/hbomax.ini
; ruleset=🎶 TikTok,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TikTok.list
;ruleset=🌏 ChinaMedia,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list

ruleset=📢 Google,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=📢 Google,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
ruleset=📢 Google,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=Ⓜ️ Microsoft,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ Microsoft,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 Apple,https://gh.monlor.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=🎮 GamePlatform,https://gh.monlor.com/https://raw.githubusercontent.com/LM-Firefly/Rules/master/Game.list

;final
ruleset=🐟 Other,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 Default`select`[]🎯 Direct`[]♻️ Automatic`[]🚀 Manual`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 UnitedStates`[]🇩🇪 Germany`[]🇬🇧 UnitedKingdom`[]🇦🇺 Australia`[]🇨🇳 China`[]🕹️ Game
custom_proxy_group=🚀 Manual`select`.*
custom_proxy_group=♻️ Automatic`url-test`(?i)^(?!.*(家宽|游戏|抓包)).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=📢 Google`select`[]🎯 Direct`[]🚀 Default`[]♻️ Automatic`[]🚀 Manual`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 UnitedStates`[]🇩🇪 Germany`[]🇬🇧 UnitedKingdom`[]🇦🇺 Australia`[]🇨🇳 China
custom_proxy_group=Ⓜ️ Microsoft`select`[]🎯 Direct`[]🚀 Default`[]♻️ Automatic`[]🚀 Manual`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 UnitedStates`[]🇩🇪 Germany`[]🇬🇧 UnitedKingdom`[]🇦🇺 Australia`[]🇨🇳 China
custom_proxy_group=🍎 Apple`select`[]🎯 Direct`[]🚀 Default`[]♻️ Automatic`[]🚀 Manual`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 UnitedStates`[]🇩🇪 Germany`[]🇬🇧 UnitedKingdom`[]🇦🇺 Australia`[]🇨🇳 China

custom_proxy_group=💳 Wallet`select`[]🎯 Direct`[]🚀 Default`[]♻️ Automatic`[]🚀 Manual`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 UnitedStates`[]🇩🇪 Germany`[]🇬🇧 UnitedKingdom`[]🇦🇺 Australia`[]🇨🇳 China`.*
custom_proxy_group=🤖 AITools`select`[]🎯 Direct`[]🚀 Default`[]♻️ Automatic`[]🚀 Manual`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 UnitedStates`[]🇩🇪 Germany`[]🇬🇧 UnitedKingdom`[]🇦🇺 Australia`.*

custom_proxy_group=🌍 Streaming`select`[]🎯 Direct`[]🚀 Default`[]♻️ Automatic`[]🚀 Manual`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 UnitedStates`[]🇩🇪 Germany`[]🇬🇧 UnitedKingdom`[]🇦🇺 Australia`[]🇨🇳 China
custom_proxy_group=📺 Bahamut`select`[]🇹🇼 Taiwan`[]🎯 Direct`[]🚀 Default`[]🚀 Manual
custom_proxy_group=🎮 GamePlatform`select`[]🎯 Direct`[]🚀 Default`[]♻️ Automatic`[]🚀 Manual`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 UnitedStates`[]🇩🇪 Germany`[]🇬🇧 UnitedKingdom`[]🇦🇺 Australia`[]🇨🇳 China
custom_proxy_group=🗺️ AppleRegion`select`[]🎯 Direct`[]🚀 Default`[]♻️ Automatic`[]🚀 Manual`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 UnitedStates`[]🇩🇪 Germany`[]🇬🇧 UnitedKingdom`[]🇦🇺 Australia`[]🇨🇳 China`.*
custom_proxy_group=🔌 TCPPorts`select`[]🎯 Direct`[]🚀 Default`[]♻️ Automatic`[]🚀 Manual`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 UnitedStates`[]🇩🇪 Germany`[]🇬🇧 UnitedKingdom`[]🇦🇺 Australia`[]🇨🇳 China`.*

custom_proxy_group=🇨🇳 CNService`select`[]🎯 Direct`[]🇨🇳 China`[]🚀 Default`[]🚀 Manual

custom_proxy_group=🛑 Advert`select`[]REJECT`[]🎯 Direct`[]🚀 Manual
custom_proxy_group=🐟 Other`select`[]🎯 Direct`[]🚀 Default`[]♻️ Automatic`[]🚀 Manual`[]🇭🇰 HongKong`[]🇹🇼 Taiwan`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇺🇲 UnitedStates`[]🇩🇪 Germany`[]🇬🇧 UnitedKingdom`[]🇦🇺 Australia`[]🇨🇳 China

custom_proxy_group=🇨🇳 China`url-test`(?i)^(?!.*(家宽|游戏|抓包|HOME|GAME|FORWARD)).*(中国|CN).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇭🇰 HongKong`url-test`(?i)^(?!.*(家宽|游戏|抓包|HOME|GAME|FORWARD)).*(香港|港|HK|Hong Kong).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇹🇼 Taiwan`url-test`(?i)^(?!.*(家宽|游戏|抓包|HOME|GAME|FORWARD)).*(台湾|台北|TW|Taiwan).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 Japan`url-test`(?i)^(?!.*(家宽|游戏|抓包|HOME|GAME|FORWARD)).*(日本|东京|大阪|泉日|埼玉|JP|Japan).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 UnitedStates`url-test`(?i)^(?!.*(家宽|游戏|抓包|HOME|GAME|FORWARD)).*(美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 Singapore`url-test`(?i)^(?!.*(家宽|游戏|抓包|HOME|GAME|FORWARD)).*(新加坡|坡|狮城|SG|Singapore).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇩🇪 Germany`url-test`(?i)^(?!.*(家宽|游戏|抓包|HOME|GAME|FORWARD)).*(德国|DE|Germany).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇬🇧 UnitedKingdom`url-test`(?i)^(?!.*(家宽|游戏|抓包|HOME|GAME|FORWARD)).*(英国|UK|United Kingdom).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇦🇺 Australia`url-test`(?i)^(?!.*(家宽|游戏|抓包|HOME|GAME|FORWARD)).*(澳大利亚|澳洲|AU|Australia).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🕹️ Game`url-test`(游戏|GAME)`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🎯 Direct`select`[]DIRECT

enable_rule_generator=true
overwrite_original_rules=true
