DOMAIN-SUFFIX,monlor.com
DOMAIN,raw.githubusercontent.com
# apple
DOMAIN-SUFFIX,push.apple.com
# bambu
DOMAIN-SUFFIX,bambulab.com
DOMAIN-SUFFIX,makerworld.com
# linkedin
DOMAIN-SUFFIX,linkedin.com
# google
DOMAIN,services.googleapis.cn
