# general
DOMAIN-SUFFIX,prod.ondemandconnectivity.com
DOMAIN-SUFFIX,pub.3gppnetwork.org

# additional rules not covered by pub.3gppnetwork.org
DOMAIN,epdg.ims.2degrees.net.nz
DOMAIN,epdg.epc.mnc005.mcc530.pub.3gppnetwork.spark.co.nz
IP-CIDR,203.87.128.0/17,no-resolve
IP-CIDR,87.194.0.0/16,no-resolve
